openapi: 3.0.3
info:
  title: СБЕР админка
  description: Обеспечение работы пользовательского интерфейса проекта "СБЕР админка"
  version: 0.2.0
  contact:
    name: avbx

servers:
  - url: 'http://localhost:8080'
    description: Development server
  - url: 'http://localhost:8080'
    description: Local run server
  - url: 'http://localhost:8080'
    description: Productive server
  - url: 'http://localhost:8080'
    description: Test server

paths:

  /auth/login:
    post:
      description: Вход пользователя
      operationId: login
      tags:
        - Authz
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequestMessage"
      responses:
        200:
          description: Авторизация прошла успешно
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponseMessage"
        400:
          description: Недопустимые параметры вызова
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseError"
        401:
          description: Пользователь ввел неверный адрес и/или пароль


  /client/create:
    post:
      description: Создание дового клиента
      operationId: addNewClient
      tags:
        - Client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClientInfo"
      responses:
        200:
          description: Слиент создан
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientInfo"
        400:
          description: Недопустимые параметры вызова
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseError"
        401:
          description: Пользователь не авторизирован

  /client:
    get:
      description: Получение списка клиентов
      operationId: getListClientInfo
      tags:
        - Client
      parameters:
        - $ref: '#/components/parameters/pageParams'
      responses:
        200:
          description: Список клиентов
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientInfoPageable"
        400:
          description: Недопустимые параметры вызова
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseError"
        401:
          description: Пользователь не авторизирован

  /client/{clientId}:
    get:
      description: Получение одного клиента
      operationId: getClientInfoById
      tags:
        - Client
      parameters:
        - $ref: "#/components/parameters/clientId"
      responses:
        200:
          description: Информация о клиенте
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientInfo"
        400:
          description: Недопустимые параметры вызова
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseError"
        401:
          description: Пользователь не авторизирован

components:

  parameters:

    clientId:
      in: path
      name: clientId
      description: Идентификатор слиента
      required: true
      schema:
        type: integer
        format: int32

    pageParams:
      in: query
      name: pageParams
      description: Параметры страницы с данными
      required: false
      schema:
        $ref: '#/components/schemas/PageParams'

  schemas:

    PageParams:
      description: Параметры страницы с данными
      type: object
      properties:
        pageSize:
          description: Количество элементов на странице
          type: integer
          minimum: 1
          maximum: 100
        pageCurrent:
          description: Номер текущей страницы
          type: integer
          minimum: 1
        pageTotal:
          description: Общее количество страниц
          type: integer

    ApiResponseError:
      description: Расширенная информация об ошибке
      type: object
      required:
        - timestamp
        - type
        - title
        - status
      properties:
        timestamp:
          type: string
          format: 'date-time'
          description: Метка времени ответа
        type:
          type: string
          description: URI идентификатор категоризации ошибки
        title:
          type: string
          description: Краткое сообщение об ошибке
        status:
          type: integer
          format: int64
          description: HTTP код ответа
        detail:
          type: string
          description: Полное сообщение об ошибке
        errorObject:
          type: string
          description: Какой объект сломан при запросе
        errorNodes:
          description: Детали, где произошла ошибка
          type: array
          items:
            $ref: '#/components/schemas/ApiErrorNode'
        instance:
          type: string
          description: URI идентифицирует конретное место возникновения ошибки

    ApiErrorNode:
      type: object
      description: Описание деталей ошибки
      properties:
        node:
          type: string
          description: Путь к ноде
        error:
          type: string
          description: Техническое описание ошибки
        message:
          type: string
          description: Сообщение об ошибке

    LoginResponseMessage:
      type: object
      properties:
        token:
          type: string
        tokenType:
          type: string

    LoginRequestMessage:
      description: Запрос сообщение на вход в систему
      type: object
      required:
        - mail
        - password
      properties:
        mail:
          description: Адрес электронной почты
          type: string
          format: email
          minLength: 1
          maxLength: 100
        password:
          description: Пароль
          type: string
          minLength: 10
          maxLength: 300

    ClientInfo:
      description: Информация о клиенте для создания и отображения
      type: object
      required:
        - lastName
        - surName
        - memberShipNumber
      properties:
        lastName:
          description: имя клиента
          type: string
          maximum: 1
          maxLength: 250
        surName:
          description: фамилия клиента
          type: string
          maximum: 1
          maxLength: 250
        midleName:
          description: отчество клиента
          type: string
          maximum: 1
          maxLength: 250
        phone:
          description: Номер телефона
          type: string
          minLength: 11
          maxLength: 11
        memberShipNumber:
          description: Номер абонемента
          type: string
        mail:
          description: Адрес электронной почты
          type: string
          format: email
          minLength: 1
          maxLength: 100
        memberShipDateStart:
          description: Дата начала действия абонемента
          type: string
          format: 'date-time'
        memberShipDateEnd:
          description: Дата окончания действия абонемента
          type: string
          format: 'date-time'
        isActive:
          description: Активен адонемент или нет
          type: boolean

    ClientInfoPageable:
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/ClientInfo'
        pageParams:
          $ref: '#/components/schemas/PageParams'
